# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
---
version: 2.1
jobs:     
  test_build:
    working_directory: ~/Waves/iOS
    macos:
      xcode: "10.2.0"      
    environment:
      BUNDLER_VERSION: 2.0.1
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: waves_test
    shell: /bin/bash --login -eo pipefail
    steps:
      - add_ssh_keys:
          fingerprints:
            - "43:eb:59:d6:49:f1:ae:81:cb:5a:ba:b8:01:64:19:39"
      - checkout
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          name: "Restore Gemfile"
      - restore_cache:
          key: 1-gems-{{ checksum "Podfile.lock" }}
          name: "Restore Podfile"     
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            sudo gem install bundler      
      - run:
          name: Bundle install or check
          command: bundle check || bundle install --path vendor/bundle
      - save_cache:
          name: Save cache Bundle
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Bundle check loogger
          command: |
            ls -a             
      - run:
          name: CocoaPods Repo Install
          command: bundle exec pod check || curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf            
      - run:
          name: CocoaPods install or check
          command: bundle exec pod check || bundle exec pod install
      - save_cache:
          name: Save cache Pods
          key: 1-gems-{{ checksum "Podfile.lock" }}
          paths:
            - Pods
            - WavesWallet-iOS.xcworkspace      
            - /Pods
            - /WavesWallet-iOS.xcworkspace
      - run:
          name: Fastlane download env
          command: bundle exec fastlane download_bundle_enviroments --verbose 
      - run:
          name: Fastlane Build
          command: bundle exec fastlane test_build_projet --verbose
          no_output_timeout: 60m
      - run:
          name: Fastlane Upload to Testflight
          command: bundle exec fastlane test_upload_testflight --verbose
          no_output_timeout: 60m
      - store_artifacts:
          path: Output
      - store_test_results:
          path: Output/Test
  prod_build:
    working_directory: ~/Waves/iOS
    macos:
      xcode: "10.2.0"      
    environment:
      BUNDLER_VERSION: 2.0.1
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: waves_test
    shell: /bin/bash --login -eo pipefail
    steps:
      - add_ssh_keys:
          fingerprints:
            - "43:eb:59:d6:49:f1:ae:81:cb:5a:ba:b8:01:64:19:39"
      - checkout
      - restore_cache:
          key: gems-{{ checksum "Gemfile.lock" }}
          name: "Restore Gemfile"
      - restore_cache:
          key: pods-{{ checksum "Podfile.lock" }}
          name: "Restore Podfile"     
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            sudo gem install bundler      
      - run:
          name: Bundle install or check
          command: bundle check || bundle install --path vendor/bundle
      - save_cache:
          name: Save cache Bundle
          key: gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Bundle check loogger
          command: |
            ls -a             
      - run:
          name: CocoaPods Repo Install
          command: bundle exec pod check || curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf            
      - run:
          name: CocoaPods install or check
          command: bundle exec pod check || bundle exec pod install
      - save_cache:
          name: Save cache Pods
          key: pods-{{ checksum "Podfile.lock" }}
          paths:
            - Pods
            - WavesWallet-iOS.xcworkspace      
            - ./Pods
            - ./WavesWallet-iOS.xcworkspace
      - run:
          name: Bundle check loogger
          command: |
            ls -a 
      - run:
          name: Fastlane download env
          command: bundle exec fastlane download_bundle_enviroments --verbose 
      - run:
          name: Fastlane Build
          command: bundle exec fastlane prod_build_projet --verbose
          no_output_timeout: 60m
      - run:
          name: Fastlane Upload to Testflight
          command: bundle exec fastlane prod_upload_testflight --verbose
          no_output_timeout: 60m
      - store_artifacts:
          path: Output
      - store_test_results:
          path: Output/Test                
  Test:
    macos:
        xcode: "10.2.0"
    working_directory: ~/Waves/iOS
    environment:
      BUNDLER_VERSION: 2.0.1
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: waves_test
    shell: /bin/bash --login -eo pipefail
    steps:
      - add_ssh_keys:
          fingerprints:
            - "43:eb:59:d6:49:f1:ae:81:cb:5a:ba:b8:01:64:19:39"
      - checkout
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          name: "Restore Gemfile"
      - restore_cache:
          key: 1-gems-{{ checksum "Podfile.lock" }}
          name: "Restore Podfile"     
      - restore_cache:
          key: 1-repos-{{ checksum "Podfile.lock" }}
          name: "Restore Repos"         
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            sudo gem install bundler
      - run:
          name: Bundle install or check
          command: bundle check || bundle install --path vendor/bundle
      - save_cache:
          name: Save cache Bundle
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: CocoaPods Repo Install
          command: bundle exec pod check || curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf            
      - run:
          name: CocoaPods install or check
          command: bundle exec pod check || bundle exec pod install
      - save_cache:
          name: Save cache Pods
          key: 1-gems-{{ checksum "Podfile.lock" }}
          paths:
            - /Pods
            - /WavesWallet-iOS.xcworkspace
      - save_cache:
          name: Save cache Repos
          key: 1-repos-{{ checksum "Podfile.lock" }}
          paths:
            - ~/.cocoapods/repos            
      - run:
          name: Fastlane download env
          command: bundle exec fastlane download_bundle_enviroments --verbose   
      - run:
          name: Fastlane Build
          command: bundle exec fastlane test_build_projet --verbose
          no_output_timeout: 60m
      - run:
          name: Bundle Ls a
          command: ls -a
      - run:
          name: Fastlane Upload to Testflight
          command: bundle exec fastlane test_upload_testflight --verbose
          no_output_timeout: 60m
      - store_artifacts:
          path: Maks
      - store_test_results:
          path: Maks/P
workflows:
  version: 2.1
  Release:
    jobs:
      - prod_build:          
          filters:
            branches:
              only: feature/10
  Test:
    jobs:
      - test_build:          
          filters:
            branches:
              only: feature/10