# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
---
version: 2
jobs:
  rocketjump:
    macos:
        xcode: "10.0.0"
    docker:
      - image: circleci/ruby
    working_directory: ~/Waves/iOS
    environment:
      FL_OUTPUT_DIR: ~/Waves/iOS/Output
      FASTLANE_LANE: waves_test
    shell: /bin/bash --login -o pipefail
    steps:
      - add_ssh_keys:
          fingerprints:
            - "43:eb:59:d6:49:f1:ae:81:cb:5a:ba:b8:01:64:19:39"
      - checkout
      - run:
          name: Set Ruby Version
          command:  echo "ruby-2.3" > ~/.ruby-version
      - run:
          name: SSH
          command: ls -la ~/.ssh/
      - run:
          name: SSH Cat config
          command: cat ~/.ssh/config
      - run:
          name: Bundle
          command: bundle install
      - run:
          name: Fastlane action setup_circle_ci
          command: bundle exec fastlane action setup_circle_ci --verbose
      - run:
          name: Fastlane certificates
          command: bundle exec fastlane certificates --verbose
      - run:
          name: Fastlane Build
          command: bundle exec fastlane $FASTLANE_LANE --verbose
      - store_artifacts:
          path: ~/Waves/iOS/Output
      - store_test_results:
          path: ~/Waves/iOS/Output/Results
workflows:
  version: 2
  sakura:
    jobs:
      - rocketjump
