# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
---
version: 2
jobs:
  Test:
    macos:
        xcode: "10.0.0"
    working_directory: ~/Waves/iOS
    environment:
      BUNDLER_VERSION: 2.0.1
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: waves_test
    shell: /bin/bash --login -eo pipefail
    steps:
      - add_ssh_keys:
          fingerprints:
            - "43:eb:59:d6:49:f1:ae:81:cb:5a:ba:b8:01:64:19:39"
      - checkout
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          name: "Restore Gemfile"
      - restore_cache:
          key: 1-gems-{{ checksum "Podfile.lock" }}
          name: "Restore Podfile"            
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            sudo gem install bundler      
      - run:
          name: Bundle install or check
          command: bundle check || bundle install --path Temp/vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - Temp/vendor/bundle
      - run:
          name: CocoaPods Repo Install
          command: bundle exec pod check || curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf            
      - run:
          name: CocoaPods install or check
          command: bundle exec pod check || bundle exec pod install
      - save_cache:
          key: 1-gems-{{ checksum "Podfile.lock" }}
          paths:
            - /Pods
            - /WavesWallet-iOS.xcworkspace
            - Pods
            - WavesWallet-iOS.xcworkspace
            - ~/.cocoapods/repos
      - run:
          name: Fastlane download env
          command: bundle exec fastlane download_bundle_enviroments --verbose   
      - run:
          name: Fastlane Build
          command: bundle exec fastlane $FASTLANE_LANE --verbose
          no_output_timeout: 60m
      - store_artifacts:
          path: Maks
      - store_test_results:
          path: Maks/P
  Release:
    macos:
        xcode: "10.0.0"
    working_directory: ~/Waves/iOS
    environment:
      BUNDLER_VERSION: 2.0.1
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: waves
    shell: /bin/bash --login -eo pipefail
    steps:
      - add_ssh_keys:
          fingerprints:
            - "43:eb:59:d6:49:f1:ae:81:cb:5a:ba:b8:01:64:19:39"
      - checkout
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}      
      - run:
          name: SSH
          command: ls -la ~/.ssh/
      - run:
          name: SSH Cat config
          command: cat ~/.ssh/config
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            sudo gem install bundler
      - run:
          name: Fastlane download env
          command: bundle exec fastlane download_bundle_enviroments --verbose
      - run:
          name: Bundle
          command: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Fastlane download env
          command: bundle exec fastlane download_bundle_enviroments --verbose                        
      - run:
          name: Fastlane Build
          command: bundle exec fastlane $FASTLANE_LANE --verbose
          no_output_timeout: 60m
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
  Test_fabric:
    macos:
        xcode: "10.0.0"
    working_directory: ~/Waves/iOS
    environment:
      BUNDLER_VERSION: 2.0.1
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: waves_test_adhoc
    shell: /bin/bash --login -eo pipefail
    steps:
      - add_ssh_keys:
          fingerprints:
            - "43:eb:59:d6:49:f1:ae:81:cb:5a:ba:b8:01:64:19:39"
      - checkout
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}      
      - run:
          name: SSH
          command: ls -la ~/.ssh/
      - run:
          name: SSH Cat config
          command: cat ~/.ssh/config      
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            sudo gem install bundler
      - run:
          name: Fastlane download env
          command: bundle exec fastlane download_bundle_enviroments --verbose          
      - run:
          name: Bundle
          command: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Fastlane download env
          command: bundle exec fastlane download_bundle_enviroments --verbose            
      - run:
          name: Fastlane Build
          command: bundle exec fastlane $FASTLANE_LANE --verbose
          no_output_timeout: 60m
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
workflows:
  version: 2
  Spaceship:
    jobs:
      - Test:
          filters:
            branches:
              only: /^release/v.{2,}$/
      - Release:
          filters:
            branches:
              only: /^release/v.{2,}$/ 